version: '3.1'

services:
  db:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6601:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dingo